young kim profile update
getfutureproof/fp_study_notes_hello_github pull request #1163
Opened 2022-12-12 18:43 UTC by CKIMM7

added cv

2022-12-14 09:30 UTC, CKIMM7 commented
added video

2022-12-16 16:52 UTC, rom-30 requested changes

2022-12-16 16:52 UTC, rom-30 commented on sholes/roster.json
> +          }
Can you please replace `"url": "https://youtu.be/dddrxqmlBJs"` with `"url": "dddrxqmlBJs"` :) ?

2022-12-22 12:56 UTC, senavarro submitted a review, later dismissed

2022-12-22 13:05 UTC, merged