Update Anna H - video url
getfutureproof/fp_study_notes_hello_github pull request #1168
Opened 2022-12-14 09:29 UTC by anaxz

2022-12-16 16:55 UTC, rom-30 requested changes

2022-12-16 16:55 UTC, rom-30 commented on sholes/roster.json
>            }]
Can you please replace 
            "url": "https://www.youtube.com/watch?v=drvQAtbSZvw"
with      "url": "drvQAtbSZvw"

2022-12-22 12:13 UTC, senavarro approved these changes

2022-12-22 12:14 UTC, merged

2022-12-22 12:14 UTC, senavarro commented
She did fix it but Romeo is OOO so I reviewed, approved and merged.