changes to bhatt roster
getfutureproof/fp_study_notes_hello_github pull request #413
Opened 2022-01-27 09:51 UTC by asafoadjeif

2022-01-27 11:12 UTC, rom-30 requested changes
Hi @asafoadjeif,

I can see that you are thinking ahead but please only add type: cv

2022-01-27 16:15 UTC, rom-30 submitted a review, later dismissed
Where is the id for the video?

2022-01-27 19:38 UTC, asafoadjeif commented
>Hi @rom-30 I was under the impression that the video url worked as an id?

2022-01-28 05:28 UTC, rom-30 approved these changes

2022-01-28 05:28 UTC, merged