Update roster.json
getfutureproof/fp_study_notes_hello_github pull request #552
Opened 2022-03-14 15:07 UTC by Scralfie

2022-03-14 15:49 UTC, rom-30 requested changes

2022-03-14 15:49 UTC, rom-30 commented on gebru/roster.json
> +    }
You need to add a comma between both objects :)

2022-03-15 14:40 UTC, rom-30 requested changes

2022-03-15 14:40 UTC, rom-30 commented on gebru/roster.json
> +    }
I unresolved the conversation because you still need to make the changes :)

2022-03-17 10:33 UTC, Scralfie reviewed
Is this ok?

2022-03-17 11:01 UTC, merged