Gebru cohort David Quigley vid cv
getfutureproof/fp_study_notes_hello_github pull request #674
Opened 2022-04-27 22:20 UTC by AverKill

2022-04-28 08:33 UTC, rom-30 requested changes

2022-04-28 08:33 UTC, rom-30 commented on gebru/roster.json
> +          "url": "https://youtu.be/jVLV4fjyDls"
@AverKill 
I know the name of the key is misleading, but can you please replace the full url with the video_id
i.e, "url": "jVLV4fjyDls"

2022-04-28 15:49 UTC, AverKill reviewed
Made the change please have a look

2022-04-29 10:15 UTC, rom-30 approved these changes

2022-04-29 10:15 UTC, merged