add Syedul Jakerin Ahmed
getfutureproof/fp_study_notes_hello_github pull request #961
Opened 2022-08-01 12:32 UTC by jakerinahmed

request review from @getfutureproof-admin

2022-08-01 12:37 UTC, rom-30 requested changes

2022-08-01 12:37 UTC, rom-30 commented on shaw/roster.json
> +      },
Please remove the trailing comma :)

2022-08-02 11:30 UTC, jakerinahmed commented
request review from @getfutureproof-admin

2022-08-02 12:39 UTC, rom-30 approved these changes
Thanks @jakerinahmed

2022-08-02 12:39 UTC, merged